map $ssl_preread_server_name $upstream {
    pwa-utt-jaime.duckdns.org              127.0.0.1:3001;
    198.71.54.179.nip.io                   127.0.0.1:3002;
    packstock.198.71.54.179.nip.io         127.0.0.1:8443;
    default                                127.0.0.1:3001;
}

server {
    listen 443;
    proxy_pass $upstream;
    ssl_preread on;
}
