# Generated by Django 5.2.10 on 2026-01-16 05:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_consumable', models.BooleanField(default=False, help_text='Los materiales de esta categoría son consumibles (se manejan por stock y no se devuelven)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('exterior_number', models.CharField(max_length=50)),
                ('interior_number', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(default='México', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_of_measure', models.CharField(choices=[('unit', 'Unidad'), ('set', 'Conjunto'), ('box', 'Caja'), ('package', 'Paquete'), ('meter', 'Metro'), ('kg', 'Kilogramo'), ('liter', 'Litro')], default='unit', max_length=50)),
                ('min_stock_level', models.IntegerField(default=0, help_text='Nivel mínimo de stock. Alerta cuando available_quantity <= min_stock_level', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.IntegerField(default=0, help_text='Cantidad sugerida para reordenar cuando stock esté bajo', validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('on_loan', 'En préstamo'), ('maintenance', 'En mantenimiento'), ('damaged', 'Dañado'), ('retired', 'Retirado')], default='available', max_length=50)),
                ('is_available_for_loan', models.BooleanField(default=True)),
                ('requires_facial_auth', models.BooleanField(default=False, help_text='Requiere autenticación facial para préstamos')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.location')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['account', 'is_active'], name='materials_c_account_e71629_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['account', 'name'], name='materials_c_account_fd60be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('account', 'name')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['account', 'is_active'], name='materials_l_account_a64996_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['account', 'name'], name='materials_l_account_97ede7_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['account', 'is_active'], name='materials_m_account_2bef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['account', 'category'], name='materials_m_account_7035ea_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['account', 'location'], name='materials_m_account_df9982_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['qr_code'], name='materials_m_qr_code_01d330_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['sku'], name='materials_m_sku_333099_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status'], name='materials_m_status_f9f35a_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_available_for_loan'], name='materials_m_is_avai_7ec0de_idx'),
        ),
    ]
