# Generated by Django 5.2.10 on 2026-01-21 03:54

import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=materials.models.qr_upload_to),
        ),
    ]
