# Generated by Django 5.0 on 2026-02-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
