# Generated by Django 5.0 on 2026-02-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del material', null=True, upload_to='materials/'),
        ),
    ]
