# Generated by Django 5.0 on 2026-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Número de serie para materiales no consumibles', max_length=255, null=True),
        ),
    ]
