# Generated by Django 5.2.10 on 2026-01-16 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('exterior_number', models.CharField(blank=True, max_length=50)),
                ('interior_number', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='México', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscription_plan', models.CharField(choices=[('freemium', 'Freemium'), ('premium', 'Premium')], default='freemium', max_length=50)),
                ('max_locations', models.IntegerField(default=1)),
                ('max_users', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'indexes': [models.Index(fields=['is_active'], name='accounts_is_acti_5b02bd_idx'), models.Index(fields=['subscription_plan'], name='accounts_subscri_417b66_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('inventarista', 'Inventarista'), ('employee', 'Empleado')], default='employee', max_length=50)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.account')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['account'], name='users_account_f80812_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'), models.Index(fields=['is_blocked'], name='users_is_bloc_7a912f_idx')],
            },
        ),
    ]
