# Generated by Django 5.0 on 2026-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa para etiquetas', null=True, upload_to='account_logos/'),
        ),
    ]
