# Generated by Django 5.0 on 2026-02-13 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monthly', 'Plan Mensual'), ('quarterly', 'Plan Trimestral'), ('annual', 'Plan Anual')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('max_users', models.IntegerField(default=-1)),
                ('max_locations', models.IntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='subscription_plan',
            field=models.CharField(choices=[('freemium', 'Freemium'), ('monthly', 'Plan Mensual'), ('quarterly', 'Plan Trimestral'), ('annual', 'Plan Anual')], default='freemium', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='completed', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.account')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.subscriptionplan')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['account'], name='payments_account_d84590_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx')],
            },
        ),
    ]
