# Generated by Django 5.0 on 2026-02-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
