# Generated by Django 4.2.7 on 2026-01-29 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('approve', 'Aprobar'), ('reject', 'Rechazar'), ('loan_issue', 'Préstamo emitido'), ('loan_return', 'Préstamo devuelto'), ('extension_request', 'Solicitud de extensión'), ('extension_approved', 'Extensión aprobada'), ('extension_rejected', 'Extensión rechazada'), ('material_consume', 'Material consumido'), ('stock_update', 'Actualización de stock')], max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON con los cambios: {campo: {old: valor_anterior, new: valor_nuevo}}', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='audit_audit_account_0a06e9_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['table_name', 'record_id'], name='audit_audit_table_n_dc0494_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
