# Generated by Django 4.2.7 on 2026-01-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('layout', models.JSONField(default=dict, help_text='\n        Estructura JSON del layout:\n        {\n            "type": "standard",\n            "show_logo": true,\n            "show_company_name": true,\n            "show_material_name": true,\n            "show_sku": true,\n            "show_category": true,\n            "show_location": true,\n            "qr_size": "medium",\n            "text_size": "small",\n            "custom_fields": ["field1", "field2"]\n        }\n        ')),
                ('is_default', models.BooleanField(default=False)),
                ('width_mm', models.IntegerField(default=50, help_text='Ancho en milímetros')),
                ('height_mm', models.IntegerField(default=30, help_text='Alto en milímetros')),
                ('print_settings', models.JSONField(blank=True, default=dict, help_text='\n        Configuración de impresión:\n        {\n            "dpi": 300,\n            "paper_size": "A4",\n            "labels_per_sheet": 21,\n            "margin_top": 10,\n            "margin_left": 10,\n            "margin_right": 10,\n            "margin_bottom": 10\n        }\n        ')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Plantilla de Etiqueta',
                'verbose_name_plural': 'Plantillas de Etiquetas',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['account', 'is_active'], name='labels_labe_account_f32438_idx'), models.Index(fields=['account', 'is_default'], name='labels_labe_account_030968_idx')],
            },
        ),
    ]
