# Generated by Django 5.2.10 on 2026-01-16 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('new_return_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extensión de Préstamo',
                'verbose_name_plural': 'Extensiones de Préstamo',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('desired_pickup_date', models.DateField()),
                ('desired_return_date', models.DateField()),
                ('purpose', models.TextField(blank=True, help_text='Propósito del préstamo', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Préstamo',
                'verbose_name_plural': 'Solicitudes de Préstamo',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de Solicitud',
                'verbose_name_plural': 'Items de Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_loaned', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_returned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_consumable_loan', models.BooleanField(default=False, help_text='Si es consumible, se reduce el stock permanentemente y no requiere devolución')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('facial_auth_verified', models.BooleanField(default=False)),
                ('facial_auth_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_signature', models.TextField(blank=True, help_text='Firma digital en base64', null=True)),
                ('return_signature', models.TextField(blank=True, help_text='Firma digital en base64', null=True)),
                ('condition_on_pickup', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo'), ('damaged', 'Dañado')], default='good', max_length=50)),
                ('condition_on_return', models.CharField(blank=True, choices=[('excellent', 'Excelente'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo'), ('damaged', 'Dañado')], max_length=50, null=True)),
                ('damage_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('returned', 'Devuelto'), ('overdue', 'Vencido'), ('lost', 'Extraviado')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.account')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loans', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(limit_choices_to={'user_type': 'inventarista'}, on_delete=django.db.models.deletion.CASCADE, related_name='issued_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-issued_at'],
            },
        ),
    ]
