# Generated by Django 5.2.10 on 2026-01-16 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='materials.material'),
        ),
        migrations.AddField(
            model_name='loan',
            name='returned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'inventarista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanextension',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loanextension',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanextension',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'inventarista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'inventarista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.loanrequest'),
        ),
        migrations.AddField(
            model_name='loanrequestitem',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loans.loanrequest'),
        ),
        migrations.AddField(
            model_name='loanrequestitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_request_items', to='materials.material'),
        ),
        migrations.AddIndex(
            model_name='loanextension',
            index=models.Index(fields=['loan', 'status'], name='loans_loane_loan_id_99767c_idx'),
        ),
        migrations.AddIndex(
            model_name='loanextension',
            index=models.Index(fields=['status'], name='loans_loane_status_34ccad_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['account', 'status'], name='loans_loanr_account_a0eb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['requester', 'status'], name='loans_loanr_request_b651f8_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['desired_pickup_date'], name='loans_loanr_desired_c33aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['status'], name='loans_loanr_status_9d5059_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['account', 'status'], name='loans_loan_account_62dad9_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_loan_borrowe_d07c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['material', 'status'], name='loans_loan_materia_edc823_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['expected_return_date'], name='loans_loan_expecte_d35e46_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_request'], name='loans_loan_loan_re_1c851e_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequestitem',
            index=models.Index(fields=['loan_request'], name='loans_loanr_loan_re_f76290_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequestitem',
            index=models.Index(fields=['material'], name='loans_loanr_materia_6f7700_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanrequestitem',
            unique_together={('loan_request', 'material')},
        ),
    ]
