# Generated by Django 5.2.10 on 2026-01-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanextension',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_extensions', to='accounts.account'),
            preserve_default=False,
        ),
    ]
