# Generated by Django 5.0 on 2026-02-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_qr_token_loanrequest_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='desired_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
